### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by sircon** [markusherzog/ueberauth_spotify#3]
Hello guys,

I almost managed to fully implement this strategy in an app I'm working on but I got stuck. After getting back the callback with the code it breaks with the following message:

```no case clause matching: {:error, %OAuth2.Response{body: "{\n \"error\": {\n \"status\": 400,\n \"message\": \"Only valid bearer authentication supported\"\n }\n}", headers: [{"www-authenticate", "Bearer realm=\"spotify\", error=\"invalid_request\", error_description=\"Only valid bearer authentication supported\""}, {"access-control-allow-origin", "*"}, {"access-control-allow-headers", "Accept, App-Platform, Authorization, Content-Type, Origin, Retry-After, Spotify-App-Version"}, {"access-control-allow-methods", "GET, POST, OPTIONS, PUT, DELETE, PATCH"}, {"access-control-allow-credentials", "true"}, {"access-control-max-age", "604800"}, {"content-type", "application/json"}, {"content-length", "99"}, {"date", "Wed, 28 Aug 2019 12:43:37 GMT"}, {"via", "1.1 google"}, {"alt-svc", "clear"}], status_code: 400}}```

It seems after the log in, it gets the code back in the callback and calls the endpoint `/me` but that one doesn't have the appropriate headers.

I'm new to Phoenix and Elixir and this is as far as I could fixed it myself. Can anybody help me?

Also, I had to use `{:ueberauth_spotify, github: "markusherzog/ueberauth_spotify"}` as the package in [hex](https://hex.pm/packages/ueberauth_spotify) was quite old. I can update the Readme later.

**Comment by sircon** [comment]
Ok, with further investigation I noticed that the tokens are not being parsed as they should. This is the OAuth2.Client struct:

```
%OAuth2.Client{
  authorize_url: "https://accounts.spotify.com/authorize",
  client_id: "xxxxxxxxxxxxxxxxxxxxxx",
  client_secret: "xxxxxxxxxxxxxxxxxxxxxx",
  headers: [],
  params: %{},
  redirect_uri: "http://localhost:4000/auth/spotify/callback",
  ref: nil,
  request_opts: [],
  serializers: %{},
  site: "https://api.spotify.com/v1",
  strategy: Ueberauth.Strategy.Spotify.OAuth,
  token: %OAuth2.AccessToken{
    access_token: "{\"access_token\":\"BQAzIgjRZiAdmeObOyz8cCvEFqUUGT497NCDjRVeWgRM7-15ws7Yu9e8D9Lt_GhqYDeeO_PjEAJP913pO6brOQ0SQDvU0mCA0X2KND_7QABTNEywoQlputh_Fu75gkZFje74_BPOIO0J9ouTU9oAa79z8dG5FJlKZPM\",\"token_type\":\"Bearer\",\"expires_in\":3600,\"refresh_token\":\"AQBUgQIHev6AU_odPgBpXv8W_JFDO-67bPu9uNxPZIKrQjsD6j2744nBYUOsazsXQe2zBxEgX8vG3qn-Ee_w6uexpcJMa81htdVDR2DiJ0T7dPX9ygnGgD9pQJVgsYJKHFbRCA\",\"scope\":\"user-read-email user-read-private\"}",
    expires_at: nil,
    other_params: %{},
    refresh_token: nil,
    token_type: "Bearer"
  },
  token_method: :post,
  token_url: "https://accounts.spotify.com/api/token"
}
```

So it is sending in the headers the `Bearer` + the whole struct instead of just the token.

**Comment by markusherzog** [comment]
Thanks for writing! Could you also show the struct as it is supposed to look?

**Comment by sircon** [comment]
Just found the problem...

In the Readme it says `serializer: [{"application/json", Jason}]` and should be `serializers` instead. I think it should default to `Ueberauth.json_library()` though like [ueberauth_github](https://github.com/ueberauth/ueberauth_github/blob/master/lib/ueberauth/strategy/github/oauth.ex#L42).

I can open a PR tomorrow with a few suggestions/fixes and fix the Readme as well.

**Comment by markusherzog** [comment]
Nice find! A PR would be highly appreciated 🙂

**Comment by sircon** [comment]
You're welcome, thanks for making this repository.

I just opened the PR with a refactor and updated the readme and the deps. Let me know if you have any questions, or suggestions!

**Comment by markusherzog** [comment]
Thank you so much, that was a very beautiful PR! It's merged and I made a new release from that version
